### ISSUE TITLE
Adjust inheritance and implement item class

### ISSUE THREAD

**Issue by Sean-Nishi** [Sean-Nishi/Reluctant-Hero#187]
Implement base class for all items. Will contain properties shared by all items.
Value of item
Dialog box for picking up item/explaining effect of item

**Comment by owalk** [comment]
just get it working with coins for now, keep it versatile

**Comment by owalk** [comment]
This requires a refactor of entity inheritance making it a larger scope than expected

**Comment by owalk** [comment]
Renamed, and changed Story points from 2 to a 5
@Sean-Nishi
