### ISSUE TITLE
Add neutral Postman sprite

### ISSUE THREAD

**Issue by Sean-Nishi** [Sean-Nishi/Reluctant-Hero#262]
Neutral entities that have limited interaction with good and bad entities.
Player still interacts with neutral entities based on Consume, Throw, Destroy.
Add to different sprite groups.
When neutral items spawn, add to neutral_entities. Maybe Postman neutral NPC.

Implement Postman neutral NPC and add to neutral entities.

Neutral entities that have limited interaction with good and bad entities.
Player still interacts with neutral entities based on Consume, Throw, Destroy.
Add to neutral entity group.

**Comment by owalk** [comment]
For postman text string:

Display a text screen on player collision
grab the text to display:
filename: promptStrings.py
dict struct: {npc_prompts: {postman: {silly_text: "", hint_text: ""}}}

Save text to display in a getter
interface into HUD:
in entity, not in this issue scope"
getter setter on dict called level_text

in postman the method self.level_text = ""
"" will be set to the prompt structure string

Destroy, consume, throw a postman needs to be a thing

**Comment by owalk** [comment]
Start building prompts file that contains postman prompts.
File name should contain English - prompt - entity
entity-prompt-en.py or something
