### ISSUE TITLE
Add Minotaur bad entity

### ISSUE THREAD

**Issue by Sean-Nishi** [Sean-Nishi/Reluctant-Hero#263]
Make new state for NPC state machine called "charging".
'Attack' state stop Minotaur from moving, rotates to follow good entity/target's trajectory, then after short time, move quick for certain amount of distance as a 'charge'.

Similar code structure to other NPCs 
Thrown is similar to charge, make a charge state in NPC
make a shared method for each to call

within NPC -
set state method
charge movement method
charge animation method, reduce the animation speed for the charge

within minitour -
Collision handling
Update method
Auto move method
Load character sheet into Sprite Sheet

**Comment by owalk** [comment]
Scope increase: Loading assets for larger animation sets does not work. fixing this is 4 hours of work -> 2 story points
