### ISSUE TITLE
Implement reduced wall hitbox

### ISSUE THREAD

**Issue by owalk** [Sean-Nishi/Reluctant-Hero#88]
Implement the reduced wall hitbox defined in the spec by [Issue 87](https://github.com/Sean-Nishi/Lunk-Game/issues/87)

**Comment by owalk** [comment]
This is still an issue, and needs to be fixed

**Comment by Sean-Nishi** [comment]
Was not an issue, sprites that are created use either DynamicTile or StaticTile. Walls, fences, and other obstacle_sprites are derived from StaticTile, which does not have a hitbox offset. Only entities (player, damsel, skeleton) will have hitbox offset.
